### ISSUE TITLE
Graph does not update children size

### ISSUE THREAD

**Issue by kuzdogan** [ipfs-shipyard/ipfs-dag-builder-vis#24]
I was playing around with dag.ipfs.io and I noticed the number of children on the graph is not getting updated. Initially the graph is set to 11 children. However, it is always shown with 174 children. 

I was able to reproduce it in Chrome and Firefox, and also locally by cloning the repo.

Here are some screenshots:
![image](https://user-images.githubusercontent.com/13069972/135645207-208ff5c5-c4fb-4e0a-b652-6f9b1f477677.png)
![image](https://user-images.githubusercontent.com/13069972/135645165-96de0f6d-7905-4f28-80b5-dd0618590026.png)

Also tried locally on commit 430f648 and it worked all fine. It seems the last commit broke things.

![image](https://user-images.githubusercontent.com/13069972/135645453-2ef2571a-8cd2-4580-bd47-4a8390bf749f.png)
![image](https://user-images.githubusercontent.com/13069972/135645475-7961185f-e361-4d72-b93b-d39b364fd687.png)

The file used is QmcXVBPfq7jNjRd13BmRkJoobHw4KU4RnD5GSySnk36UWU but behaves the same with different files.

**Comment by alanshaw** [comment]
Thanks for reporting. It will be fixed by https://github.com/ipfs-shipyard/ipfs-dag-builder-vis/pull/25 soon!
