### ISSUE TITLE
Move to Fleek

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-dag-builder-vis#26]
This project is building on Fleek now, but to host it there we need to update the DNS.

Fleek expects to see a `CNAME` record for `dag.ipfs.io` to `634c28dae701e8ca2e20.b-cdn.net`.

The hold up is this requires us to delete the existing `dag.ipfs.io` zone from dnsimple and then update the `ipfs.io` zone to include the CNAME. Dnsimple does not support creating that CNAME from the `dag.ipfs.io` zone.

The site is already building to http://634c28dae701e8ca2e20.b-cdn.net/

**Comment by thattommyhall** [comment]
```
"dnslink=/ipfs/bafybeiecas3ooph4u7pepenefguoonbz7c7lhynidbz6ji2u7j2mtba56u"
```

Is what was deployed to the (about to be deleted) subdomain

**Comment by thattommyhall** [comment]
https://www.whatsmydns.net/#A/dag.ipfs.io

**Comment by thattommyhall** [comment]
https://github.com/protocol/infra/pull/814

**Comment by thattommyhall** [comment]
deleted, starting to see Bunny on whatsmydns now

**Comment by thattommyhall** [comment]
seem to need to Check then Verify the CNAME to get SSL to work

**Comment by 2color** [comment]
When moving this to Fleek, we should also migrate the URL to dag.ipfs.tech https://github.com/protocol/bifrost-infra/issues/2018

**Comment by lidel** [comment]
Resolved in https://github.com/protocol/infra/pull/944 and https://github.com/ipfs-shipyard/ipfs-dag-builder-vis/commit/f8a2e53682eba189f1871b7ea79db5f1b7878ad4
